command_timeout = 1000

[character]
error_symbol = "[âœ–](bold red) "
success_symbol = "[ï”ï”](bold #626262)"
# success_symbol = "[â¯â¯](bold #458588)"

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[directory]
truncation_length = 4
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bold #458588"
truncation_symbol = ""

[git_branch]
format = "on [$symbol$branch]($style)"
symbol = "î‚  "
style = "bold #b16286"

[git_commit]
commit_hash_length = 8
only_detached = true
format = "[\\($hash$tag\\)]($style)"
style = "bold white"
disabled = false

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
modified = "[âœ˜${count}](#fabd2f)"
staged = "[ï®${count}](#b8bb26)"
renamed = "[ï²${count}]($style)"
untracked = "[ï${count}](#458588)"
deleted = "[ï‘˜${count}](#cc241d)"
conflicted = "[â‰ ](red)"
ahead = "[ï¢${count}]($style)"
behind = "[ï£${count}]($style)"
diverged = "[ï¢${ahead_count}ï£${behind_count}]($style)"
stashed = "ğŸ“¦ "
style = "#ebdbb2"
format = '([ \[$all_status$ahead_behind\]]($style)) '

[hostname]
ssh_only = false
format = "<[$hostname]($style)>"
trim_at = "-"
style = "bold dimmed white"
disabled = true

[package]
disabled = true

[python]
format = "[$virtualenv]($style) "
style = "bold green"
disabled = false

[nodejs]
disabled = true

[golang]
disabled = true

[java]
disabled = true

[vagrant]
disabled = true

[perl]
disabled = true

[lua]
disabled = true

[terraform]
disabled = true

[cmake]
disabled = true

[dotnet]
disabled = true


[username]
style_user = "bold dimmed blue"
show_always = false
