[character]
error_symbol = "[âœ–](bold red) "
success_symbol = "[â¯â¯](bold #458588)"

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[directory]
truncation_length = 4
format = "[$path]($style)[$read_only]($read_only_style)"
style = "bold #8ec07c"
truncation_symbol = ""

[git_branch]
format = " on [$symbol$branch]($style)"
symbol = "î‚  "
style = "bold #b8bb26"

[git_commit]
commit_hash_length = 8
format = "[\\($hash$tag\\)]($style) "
style = "bold white"
disabled = false

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
conflicted = "[â‰ ](red)"
ahead = "[ï°µ${count}]($style)"
behind = "[ï°¬${count}]($style)"
diverged = "[ï°µ${ahead_count}ï°¬${behind_count}]($style)"
untracked = "[ï„¨${count}](#458588)"
stashed = "ğŸ“¦ "
modified = "[ïœ„${count}](#fabd2f)"
staged = "[ï§${count}](#b8bb26)"
renamed = "[ï£ª${count}]($style)"
deleted = "[âœ˜${count}](#cc241d)"
style = "#ebdbb2"
format = '([ \[$all_status$ahead_behind\]]($style))'

[hostname]
ssh_only = false
format = "<[$hostname]($style)>"
trim_at = "-"
style = "bold dimmed white"
disabled = true

[package]
disabled = true

[python]
format = " [$symbol$version]($style) "
style = "bold green"

[username]
style_user = "bold dimmed blue"
show_always = false
